#ifndef FENN_NEURONBASE_H
#define FENN_NEURONBASE_H

#include "FENNConfig.h"

namespace fenn
{
	enum NeuronType
	{
		NEURONTYPE_ADDITION = 0,
		NEURONTYPE_SUBTRACTION = 1,
		NEURONTYPE_MULTIPLICATION = 2,
		NEURONTYPE_DIVISION = 3,
		NEURONTYPE_TOTAL = 4,
		NEURONTYPE_UNKNOWN = 5,
	};
}

#endif